basic.forever(function () {
    profont.setYose(-1)
    profont.showString("Y")
    basic.pause(500)
    profont.setRotatation(0)
    profont.showString("abc")
    basic.pause(500)
    profont.setRotatation(1)
    profont.showString("abc")
    basic.pause(500)
    profont.setRotatation(2)
    profont.showString("abc")
    basic.pause(500)
    profont.setRotatation(3)
    profont.showString("abc")
    basic.pause(500)
})
